return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  event = { 'BufReadPre', 'BufNewFile' },
  dependencies = {
    'nvim-treesitter/nvim-treesitter-textobjects',
  },
  config = function()
    local treesitter = require 'nvim-treesitter.configs'

    treesitter.setup {
      highlight = {
        enable = true,
      },

      ident = {
        enable = true,
      },

      ensure_installed = {
        'bash',
        'c',
        'c_sharp',
        'clojure',
        'cmake',
        'cpp',
        'css',
        'csv',
        'dart',
        'diff',
        'dockerfile',
        'gdscript',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'go',
        'gomod',
        'gosum',
        'gowork',
        'graphql',
        'html',
        'htmldjango',
        'http',
        'java',
        'javascript',
        'jsdoc',
        'json',
        'kotlin',
        'latex',
        'ledger',
        'lua',
        'luadoc',
        'make',
        'markdown',
        'markdown_inline',
        'mermaid',
        'ocaml',
        'ocaml_interface',
        'php',
        'phpdoc',
        'prisma',
        'proto',
        'pug',
        'python',
        'query',
        'r',
        'regex',
        'rust',
        'scss',
        'sql',
        'svelte',
        'textproto',
        'toml',
        'tsx',
        'typescript',
        'vim',
        'vimdoc',
        'vue',
        'xml',
        'yaml',
        'zig',
      },

      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = '<C-space>',
          node_incremental = '<C-space>',
          scope_incremental = false,
          node_decremental = '<bs>',
        },
      },
    }
  end,
}
