theme = "catppuccin_mocha_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse=false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
