[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format=json", "--show-stats=false", "--issues-exit-code=1"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "html"
language-servers = [{ name = "superhtml", except-features = ["format"] }, "vscode-html-language-server", "tailwindcss-ls", "emmet-lsp"]
auto-format = true
